'use strict';
if(new URLSearchParams(location.search).has('embedded'))document.body.classList.add('embedded-runtime');
let firstStatus=true;

const api=window.AndroidLab,$=id=>document.getElementById(id);let streaming=false,frameBusy=false,dimensions={width:1,height:1},down=null,frameTimer,decoder,codecConfig,codec,videoId=null,waitingKey=true,frames=0,fpsStart=0,mode='';let availableImages=[];function imageOptions(){const tv=$('profile').value==='tv';options('image',availableImages.filter(i=>/android-tv|google-tv/.test(i.tag)===tv).map(i=>({value:i.id,label:i.id})));$('create').disabled=!$('image').options.length}
const canvas=$('screen'),ctx=canvas.getContext('2d',{alpha:false});canvas.width=1920;canvas.height=1080;ctx.fillStyle='#000';ctx.fillRect(0,0,1920,1080);ctx.fillStyle='#bdcbe3';ctx.font='32px system-ui';ctx.textAlign='center';ctx.fillText('Écran Android — activer après connexion',960,540);
async function call(action,p={}){const r=await api.command(action,p);if(!r.ok)throw Error(r.error);return r}
function report(t){$('result').textContent=t}
function options(id,items){const old=$(id).value;$(id).replaceChildren(...items.map(i=>{const o=document.createElement('option');o.value=i.value;o.textContent=i.label;return o}));if(items.some(i=>i.value===old))$(id).value=old}
async function refresh(){const s=await call('status');$('state').textContent=(s.sdk||'SDK non détecté')+'\nADB : '+(s.adb?'disponible':'absent')+' · Émulateur : '+(s.emulator?'disponible':'absent')+'\n'+s.acceleration+(s.environment?'\nAppareil : API '+s.environment.api+' · '+s.environment.abis+'\nServices Google : '+(s.environment.googleServices?'présents':'absents, vérifier les besoins de cet APK'):'');options('avd',s.avds.map(i=>({value:i.name,label:i.name+' · '+i.profile})));if(firstStatus){document.body.classList.toggle('show-android-settings',!s.devices.length);firstStatus=false;}availableImages=s.images;imageOptions();$('start').disabled=!s.emulator||!s.avds.length;options('device',s.devices.map(i=>({value:i,label:(i.startsWith('emulator-')?'Émulateur · ':'Téléphone / appareil · ')+i}))); }
function bind(id,fn){$(id).onclick=async()=>{const b=$(id);b.disabled=true;try{await fn()}catch(e){report(e.message)}finally{b.disabled=false}}}
bind('refresh',refresh);bind('sdk',async()=>{await stopStream();await call('sdk');await refresh()});window.showSelectedApk=r=>{if(r.apk)$('apk').textContent=r.apk.file+'\nPackage : '+r.apk.package+'\nAPI minimale : '+r.apk.minApi+'\nArchitecture : '+r.apk.abis+'\nLancement TV déclaré : '+(r.apk.tv?'oui':'à vérifier');};bind('pick',async()=>window.showSelectedApk(await call('pick')));
bind('listInstalled',async()=>{const r=await call('installed');options('installedPackage',r.packages.map(i=>({value:i,label:i})));});bind('launchInstalled',async()=>{const r=await call('launch-installed',{package:$('installedPackage').value});report(r.message);if(!streaming)await startStream()});
bind('create',async()=>{const r=await call('create',{profile:$('profile').value,image:$('image').value});await refresh();$('avd').value=r.name;report('Appareil créé : '+r.name)});
bind('start',async()=>{await stopStream();report('Démarrage Android… première ouverture : jusqu’à 3 minutes.');const r=await call('start',{name:$('avd').value});await refresh();$('device').value=r.serial;report('Android prêt : '+r.serial)});
bind('connect',async()=>{await stopStream();const r=await call('connect',{serial:$('device').value});await refresh();report('Appareil sélectionné : '+r.serial);await startStream()});
for(const action of ['install','launch','logs'])bind(action,async()=>{report(action==='install'?'Installation de l’APK…':'Opération Android…');const r=await call(action);report(r.message||'Terminé');if(action==='launch'&&!streaming)await startStream()});
bind('stop',async()=>{await stopStream();await call('stop');await refresh();report('Émulateur arrêté ; données conservées.')});bind('capture',async()=>{const r=await call('capture');if(r.path)report('Capture enregistrée : '+r.path)});bind('send',async()=>{await call('text',{text:$('text').value})});bind('full',()=>document.fullscreenElement?document.exitFullscreen():$('viewer').requestFullscreen());bind('close',()=>window.StudioAndroidReturn?window.StudioAndroidReturn():window.close());
function draw(source,width,height){if(canvas.width!==width||canvas.height!==height){canvas.width=width;canvas.height=height}ctx.drawImage(source,0,0,width,height);canvas.dataset.rendered='true';canvas.dataset.frames=String(++frames);const elapsed=(performance.now()-fpsStart)/1000;if(elapsed>=1){$('streamState').textContent=(mode==='video'?'Vidéo H.264':'Captures de secours')+' · '+width+' × '+height+' · '+(frames/elapsed).toFixed(1)+' images/s';}}
async function screenshot(){const r=await call('frame');dimensions={width:r.width,height:r.height};const bitmap=await createImageBitmap(await (await fetch(r.url)).blob());try{draw(bitmap,r.width,r.height)}finally{bitmap.close()}}
async function frame(){if(!streaming||mode!=='captures'||frameBusy)return;frameBusy=true;try{await screenshot()}catch(e){await stopStream();report(e.message)}finally{frameBusy=false;if(streaming&&mode==='captures')frameTimer=setTimeout(frame,150)}}
function closeDecoder(){if(decoder&&decoder.state!=='closed')decoder.close();decoder=null;codecConfig=null;codec=null;waitingKey=true;videoId=null}
async function stopStream(){streaming=false;clearTimeout(frameTimer);closeDecoder();await call('video-stop').catch(()=>{});$('live').textContent='Activer l’écran';$('streamState').textContent='Écran suspendu';mode='';}
async function fallback(error){if(!streaming||mode==='captures')return;mode='captures';closeDecoder();await call('video-stop').catch(()=>{});report('La vidéo ne peut pas démarrer : '+error+'\nMode captures activé. La fenêtre native de l’émulateur reste disponible.');if(streaming)frame()}
function spsCodec(data){for(let i=0;i+7<data.length;i++){let offset=0;if(data[i]===0&&data[i+1]===0&&data[i+2]===1)offset=3;else if(data[i]===0&&data[i+1]===0&&data[i+2]===0&&data[i+3]===1)offset=4;if(offset&&(data[i+offset]&31)===7)return 'avc1.'+[...data.subarray(i+offset+1,i+offset+4)].map(v=>v.toString(16).padStart(2,'0')).join('')}throw Error('Configuration vidéo H.264 invalide')}
api.onVideo(event=>{if(!streaming||mode!=='video')return;if(videoId!==null&&event.id!==videoId)return;if(event.type==='state'){if(event.state==='error')fallback(event.error);return}videoId=event.id;try{const data=new Uint8Array(event.data);if(event.config){codecConfig=data;const next=spsCodec(data);if(codec!==next||!decoder||decoder.state==='closed'){if(decoder&&decoder.state!=='closed')decoder.close();codec=next;decoder=new VideoDecoder({output:frame=>{try{if(streaming&&mode==='video'){if((frame.displayWidth>frame.displayHeight)!==(dimensions.width>dimensions.height))dimensions={width:dimensions.height,height:dimensions.width};draw(frame,frame.displayWidth,frame.displayHeight)}}finally{frame.close()}},error:e=>fallback(e.message)});decoder.configure({codec,optimizeForLatency:true});waitingKey=true}return}if(!decoder||!codecConfig)return;if(decoder.decodeQueueSize>6){decoder.reset();decoder.configure({codec,optimizeForLatency:true});waitingKey=true}if(waitingKey&&!event.key)return;let encoded=data;if(event.key){encoded=new Uint8Array(codecConfig.length+data.length);encoded.set(codecConfig);encoded.set(data,codecConfig.length);waitingKey=false}decoder.decode(new EncodedVideoChunk({type:event.key?'key':'delta',timestamp:event.timestamp,data:encoded}));}catch(e){fallback(e.message)}});
async function startStream(){streaming=true;frames=0;fpsStart=performance.now();$('live').textContent='Suspendre l’écran';try{await screenshot();const selected=$('streamMode').value;if(selected==='captures'){mode='captures';frame();return}if(!window.VideoDecoder)throw Error('Décodage vidéo indisponible dans cette version de Windows');mode='video';$('streamState').textContent='Connexion du flux vidéo…';await call('video-start',{quality:selected});}catch(e){await fallback(e.message)}}
bind('live',()=>streaming?stopStream():startStream());$('streamMode').onchange=async()=>{if(streaming){await stopStream();await startStream()}};
for(const b of document.querySelectorAll('[data-key]'))b.onclick=()=>call('key',{key:b.dataset.key}).catch(e=>report(e.message));
canvas.onkeydown=e=>{const k={ArrowUp:'up',ArrowDown:'down',ArrowLeft:'left',ArrowRight:'right',Enter:'ok',Escape:'back'}[e.key];if(k){e.preventDefault();call('key',{key:k}).catch(e=>report(e.message))}};
function point(e){const r=canvas.getBoundingClientRect(),scale=Math.min(r.width/canvas.width,r.height/canvas.height),w=canvas.width*scale,h=canvas.height*scale,x=(e.clientX-r.left-(r.width-w)/2)/w*dimensions.width,y=(e.clientY-r.top-(r.height-h)/2)/h*dimensions.height;if(x<0||y<0||x>=dimensions.width||y>=dimensions.height)return null;return {x:Math.floor(x),y:Math.floor(y)}}
canvas.onpointerdown=e=>{down=point(e);canvas.setPointerCapture(e.pointerId);canvas.focus()};canvas.onpointerup=e=>{const to=point(e);if(down&&to){const swipe=Math.hypot(to.x-down.x,to.y-down.y)>20;call('pointer',{...down,kind:swipe?'swipe':'tap',x2:to.x,y2:to.y}).catch(e=>report(e.message))}down=null};canvas.onpointercancel=()=>down=null;
window.addEventListener('beforeunload',()=>{clearTimeout(frameTimer);closeDecoder();api.command('video-stop').catch(()=>{})});$('profile').onchange=imageOptions;refresh().catch(e=>report(e.message));

window.refreshFromStudio=refresh;
const playCurrent=document.createElement('button');playCurrent.id='runCurrentApk';playCurrent.textContent='Installer et afficher cet APK';document.getElementById('apk').after(playCurrent);playCurrent.onclick=async()=>{playCurrent.disabled=true;try{await refresh();if(!$('device').value)throw Error('Connecter un appareil Android ou démarrer un émulateur, puis réessayer.');await call('connect',{serial:$('device').value});await call('install');await call('launch');await startStream();report('Application exécutée sur Android. Le flux affiche son véritable rendu.')}catch(e){report(e.message)}finally{playCurrent.disabled=false}};

bind('useGeometry',async()=>{const r=await call('geometry');report('Dimensions transmises à l’éditeur : '+r.profile.width+' × '+r.profile.height+' px CSS.');});

document.getElementById('toggleAndroidSettings').onclick=()=>document.body.classList.toggle('show-android-settings');

bind('wifiPair',async()=>{const code=$('wifiPairCode').value;$('wifiPairCode').value='';const r=await call('wifi-pair',{address:$('wifiPairAddress').value.trim(),code});report(r.message);});
bind('wifiConnect',async()=>{const r=await call('wifi-connect',{address:$('wifiConnectAddress').value.trim()});await refresh();$('device').value=r.serial;report(r.message);});
