const fs=require('fs'),path=require('path'),os=require('os'),crypto=require('crypto');
const {execFile,spawn}=require('child_process');
const PROFILES={phone:{width:1080,height:1920,density:420},tablet:{width:1600,height:2560,density:320},tv:{width:1920,height:1080,density:240}};
function run(file,args,timeout=30000,binary=false){return new Promise((resolve,reject)=>execFile(file,args,{shell:false,windowsHide:true,timeout,maxBuffer:16*1024*1024,encoding:binary?null:'utf8'},(error,stdout,stderr)=>{if(error)reject(new Error(String(stderr||stdout||error.message).slice(0,8000)));else resolve(stdout)}));}
function diagnose(message){const m=String(message);if(/NO_MATCHING_ABIS/i.test(m))return 'Architecture incompatible : choisir une image système correspondant aux bibliothèques natives de cet APK. '+m;if(/OLDER_SDK/i.test(m))return 'API Android trop ancienne pour cet APK. '+m;if(/UPDATE_INCOMPATIBLE/i.test(m))return 'Signature différente de la version installée. Les données existantes sont conservées ; utiliser un autre appareil virtuel. '+m;if(/MISSING_SPLIT/i.test(m))return 'APK incomplet : cette application exige plusieurs APK fractionnés. Sélectionner un APK autonome complet ; les archives APKS/XAPK ne sont pas installées par ce parcours. '+m;if(/MISSING_SHARED_LIBRARY/i.test(m))return 'Bibliothèque système requise absente (services Google ou matériel spécifique possibles). '+m;return m;}
function register({app,ipcMain,dialog,mainWindow,onGeometry}){
 let sdk='',selected=null,serial='',packageName='',busy=false,mutationBusy=false;const mutations=new Set(['sdk','pick','create','start','connect','install','launch','stop','video-start','launch-installed','wifi-pair','wifi-connect']);const launched=new Set();
 const settingsFile=()=>path.join(app.getPath('userData'),'android-lab.json');
 try{sdk=JSON.parse(fs.readFileSync(settingsFile(),'utf8')).sdk||''}catch{}
 const avdHome=()=>process.env.ANDROID_AVD_HOME||path.join(process.env.ANDROID_USER_HOME||path.join(os.homedir(),'.android'),'avd');
 const persist=()=>{fs.mkdirSync(path.dirname(settingsFile()),{recursive:true});fs.writeFileSync(settingsFile(),JSON.stringify({sdk},null,2))};
 const tool=name=>{const p=path.join(sdk,name);if(!fs.existsSync(p))throw new Error('Outil absent : '+p);return p};
 const adb=args=>run(tool('platform-tools/adb.exe'),args);
 const video=new (require('./android-video.cjs').AndroidVideo)({adb,adbPath:()=>tool('platform-tools/adb.exe'),window:mainWindow});
 app.on?.('before-quit',()=>video.stop());
 ipcMain.on?.('android:video-ack',(event,p)=>{if(event.sender===mainWindow()?.webContents&&event.senderFrame===event.sender.mainFrame&&p&&Number.isInteger(p.id)&&Number.isInteger(p.sequence))video.ack(p.id,p.sequence)});
 const device=async()=>{if(!/^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$/.test(serial))throw new Error('Sélectionner un appareil Android connecté et autorisé.');const list=await adb(['devices']);if(!list.split(/\r?\n/).some(l=>l.trim()===serial+'\tdevice'))throw new Error('Appareil hors ligne ou non autorisé.');return serial};
 const on=(name,fn)=>ipcMain.handle('android:'+name,async(event,p={})=>{if(event.sender!==mainWindow()?.webContents||event.senderFrame!==event.sender.mainFrame)return {ok:false,error:'Origine IPC refusée'};if(!p||typeof p!=='object'||Array.isArray(p))return {ok:false,error:'Paramètres invalides'};if(mutations.has(name)&&mutationBusy)return {ok:false,error:'Une opération Android est déjà en cours. Attendre sa fin.'};if(mutations.has(name))mutationBusy=true;try{return {ok:true,...await fn(p)}}catch(e){return {ok:false,error:diagnose(e.message)}}finally{if(mutations.has(name))mutationBusy=false}});
 const avds=()=>{const dir=avdHome();if(!fs.existsSync(dir))return [];return fs.readdirSync(dir).filter(n=>n.endsWith('.ini')).map(n=>{const text=fs.readFileSync(path.join(dir,n),'utf8');const folder=(text.match(/^path=(.+)$/m)||[])[1]?.trim();let config='';try{config=fs.readFileSync(path.join(folder,'config.ini'),'utf8')}catch{}return {name:n.slice(0,-4),profile:/tv|television/i.test(config)?'tv':/tablet/i.test(config)?'tablet':'phone'};});};
 const images=()=>{const out=[],base=path.join(sdk,'system-images');if(!fs.existsSync(base))return out;for(const api of fs.readdirSync(base))for(const tag of fs.readdirSync(path.join(base,api)))for(const abi of fs.readdirSync(path.join(base,api,tag)))if(fs.existsSync(path.join(base,api,tag,abi,'system.img')))out.push({id:[api,tag,abi].join('/'),api,tag,abi});return out;};
 function detectSdk(){if(sdk&&!fs.existsSync(path.join(sdk,'platform-tools','adb.exe')))sdk='';if(!sdk){const bundled=app.isPackaged?path.join(process.resourcesPath,'apk-runtime','sdk'):path.join(__dirname,'runtime','sdk');const candidates=[process.env.ANDROID_SDK_ROOT,process.env.ANDROID_HOME,bundled,path.join(process.env.LOCALAPPDATA||'', 'Android','Sdk')];const adbPath=(process.env.PATH||'').split(path.delimiter).find(p=>fs.existsSync(path.join(p,'adb.exe')));if(adbPath)candidates.push(path.dirname(adbPath));sdk=candidates.find(p=>p&&fs.existsSync(path.join(p,'platform-tools','adb.exe')))||'';if(sdk)persist();}
}
 on('status',async()=>{detectSdk();
 let devices=[];if(sdk&&fs.existsSync(path.join(sdk,'platform-tools','adb.exe')))devices=(await adb(['devices'])).split(/\r?\n/).filter(l=>/^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}\s+device$/.test(l)).map(l=>l.split(/\s/)[0]);let acceleration='Émulateur absent';if(fs.existsSync(path.join(sdk,'emulator','emulator.exe')))try{acceleration=await run(tool('emulator/emulator.exe'),['-accel-check'])}catch(e){acceleration=e.message}let environment=null;if(devices.includes(serial)){const [api,abis,google]=await Promise.all([adb(['-s',serial,'shell','getprop','ro.build.version.sdk']),adb(['-s',serial,'shell','getprop','ro.product.cpu.abilist']),adb(['-s',serial,'shell','pm','path','com.google.android.gms']).catch(()=>'')]);environment={api:api.trim(),abis:abis.trim(),googleServices:/package:/.test(google)}}return {environment,sdk,adb:fs.existsSync(path.join(sdk,'platform-tools','adb.exe')),emulator:fs.existsSync(path.join(sdk,'emulator','emulator.exe')),avds:avds(),images:images(),devices,serial,acceleration};});
 function wifiAddress(value){if(typeof value!=='string'||!/^\d{1,3}(?:\.\d{1,3}){3}:\d{1,5}$/.test(value))throw Error('Adresse attendue : IPv4:port, telle qu’affichée sur le téléphone.');const [ip,port]=value.split(':');if(ip.split('.').some(n=>Number(n)>255)||Number(port)<1||Number(port)>65535)throw Error('Adresse ou port invalide.');return value;}
 on('wifi-pair',async p=>{detectSdk();const address=wifiAddress(p.address);if(typeof p.code!=='string'||!/^\d{6}$/.test(p.code))throw Error('Le code d’association doit comporter six chiffres.');const result=await adb(['pair',address,p.code]);if(!/successfully paired/i.test(result))throw Error('Association non confirmée. Vérifie le code et le port d’association affichés sur le téléphone.');return {message:'Téléphone associé. Connecte ensuite l’adresse du débogage sans fil.'};});
 on('wifi-connect',async p=>{detectSdk();const address=wifiAddress(p.address);await adb(['connect',address]);const devices=await adb(['devices']);if(!devices.split(/\r?\n/).some(l=>l.trim()===address+'\tdevice'))throw Error('Téléphone non connecté. Vérifie le port de connexion, différent du port d’association, et le même Wi-Fi.');await video.stop();serial=address;return {serial,message:'Téléphone connecté sans câble.'};});
 on('sdk',async()=>{await video.stop();const r=await dialog.showOpenDialog({title:'Choisir le dossier Android SDK',properties:['openDirectory']});if(r.canceled)return {canceled:true};const root=fs.realpathSync(r.filePaths[0]);if(!fs.existsSync(path.join(root,'platform-tools','adb.exe')))throw new Error('Ce dossier ne contient pas platform-tools/adb.exe.');sdk=root;persist();return {sdk};});
 function aapt(){const base=path.join(sdk,'build-tools');if(!fs.existsSync(base))throw new Error('Installer Android SDK Build-Tools dans le SDK Manager pour inspecter les APK.');const versions=fs.readdirSync(base).sort((a,b)=>b.localeCompare(a,undefined,{numeric:true}));for(const v of versions){const p=path.join(base,v,'aapt.exe');if(fs.existsSync(p))return p}throw new Error('aapt.exe absent des Build-Tools.');}
 async function inspect(file){if(path.extname(file).toLowerCase()!=='.apk'||!fs.statSync(file).isFile()||fs.statSync(file).size>2*1024**3)throw new Error('Sélectionner un fichier APK valide de moins de 2 Go.');const info=await run(aapt(),['dump','badging',file]);const pkg=(info.match(/^package: name='([^']+)'/m)||[])[1];if(!pkg||!/^\w+(?:\.\w+)+$/.test(pkg))throw new Error('Identifiant Android invalide.');return {file,package:pkg,minApi:(info.match(/sdkVersion:'(\d+)'/)||[])[1],abis:(info.match(/native-code: (.+)/)||[])[1]||'Sans bibliothèque native déclarée',tv:/LEANBACK_LAUNCHER|leanback-launchable-activity|android.software.leanback/.test(info),requiredFeatures:[...info.matchAll(/^uses-feature: name='([^']+)'/gm)].map(m=>m[1]),activity:(info.match(/launchable-activity: name='([^']+)'/)||[])[1]||'',hash:await new Promise((resolve,reject)=>{const hash=crypto.createHash('sha256'),stream=fs.createReadStream(file);stream.on('data',chunk=>hash.update(chunk));stream.on('error',reject);stream.on('end',()=>resolve(hash.digest('hex')));})};}
 async function selectApk(file){detectSdk();const original=fs.realpathSync(file);if(path.extname(original).toLowerCase()!=='.apk'||!fs.statSync(original).isFile()||fs.statSync(original).size>2*1024**3)throw new Error('Sélectionner un fichier APK valide de moins de 2 Go.');const directory=path.join(app.getPath('userData'),'android-apks');fs.mkdirSync(directory,{recursive:true});const stagedFile=path.join(directory,crypto.randomUUID()+'.apk');await fs.promises.copyFile(original,stagedFile,fs.constants.COPYFILE_EXCL);try{const inspected=await inspect(stagedFile);if(selected?.stagedFile)try{fs.unlinkSync(selected.stagedFile)}catch{}selected={...inspected,file:original,stagedFile};packageName='';return {apk:{...selected,stagedFile:undefined}}}catch(error){try{fs.unlinkSync(stagedFile)}catch{}throw error}}
 on('pick',async()=>{const r=await dialog.showOpenDialog({title:'Sélectionner un APK Android',properties:['openFile'],filters:[{name:'Application Android',extensions:['apk']}]});if(r.canceled)return {canceled:true};return selectApk(r.filePaths[0])});
 on('create',async p=>{if(typeof p.profile!=='string'||!Object.hasOwn(PROFILES,p.profile))throw new Error('Profil invalide');const image=images().find(i=>i.id===p.image);if(!image)throw new Error('Sélectionner une image système installée.');if(p.profile==='tv'&&!/android-tv|google-tv/.test(image.tag))throw new Error('Android TV nécessite une véritable image Android TV / Google TV, pas une image téléphone.');if(p.profile!=='tv'&&/android-tv|google-tv/.test(image.tag))throw new Error('Cette image est réservée à Android TV.');const name='AIS_'+p.profile+'_'+crypto.randomUUID().replace(/-/g,''),dir=avdHome(),folder=path.join(dir,name+'.avd'),profile=PROFILES[p.profile];fs.mkdirSync(dir,{recursive:true});fs.mkdirSync(folder);const imageDir=path.join(sdk,'system-images',...image.id.split('/'));
 fs.writeFileSync(path.join(folder,'config.ini'),Object.entries({'AvdId':name,'avd.ini.displayname':name,'image.sysdir.1':imageDir+path.sep,'abi.type':image.abi,'hw.cpu.arch':image.abi==='x86_64'?'x86_64':image.abi,'hw.cpu.ncore':2,'hw.ramSize':2048,'hw.lcd.width':profile.width,'hw.lcd.height':profile.height,'hw.lcd.density':profile.density,'hw.keyboard':'yes','hw.gpu.enabled':'yes','hw.gpu.mode':'auto','hw.mainKeys':p.profile==='tv'?'yes':'no','hw.device.name':p.profile==='tv'?'Android TV':p.profile,'disk.dataPartition.size':'4G','showDeviceFrame':'no','skin.name':profile.width+'x'+profile.height,'tag.id':image.tag,'fastboot.forceColdBoot':'no'}).map(([k,v])=>k+'='+v).join('\n'));fs.writeFileSync(path.join(dir,name+'.ini'),'avd.ini.encoding=UTF-8\npath='+folder+'\ntarget='+image.api+'\n');return {name};});
 on('start',async p=>{if(busy)throw new Error('Démarrage déjà en cours.');if(!avds().some(a=>a.name===p.name)||!/^[-\w.]+$/.test(p.name))throw new Error('Appareil inconnu.');busy=true;try{const listing=await adb(['devices']);for(const line of listing.split(/\r?\n/)){const match=line.match(/^(emulator-\d+)\s+device$/);if(match){try{const name=(await adb(['-s',match[1],'emu','avd','name'])).split(/\r?\n/)[0].trim();if(name===p.name){serial=match[1];return {serial,reused:true}}}catch{}}}const current=listing.match(/emulator-(\d+)\s/g)||[];let port=5554;while(current.some(s=>s.includes('emulator-'+port)))port+=2;if(port>5682)throw new Error('Aucun port émulateur disponible.');const child=spawn(tool('emulator/emulator.exe'),['-avd',p.name,'-port',String(port)],{shell:false,windowsHide:true,stdio:['ignore','pipe','pipe'],detached:true});let failure='',emulatorLog='';const collect=data=>{emulatorLog=(emulatorLog+data.toString()).slice(-12000)};child.stdout.on('data',collect);child.stderr.on('data',collect);child.on('error',e=>failure=e.message);child.on('exit',c=>{if(c)failure='Émulateur arrêté, code '+c+'\n'+emulatorLog});child.unref();const target='emulator-'+port;launched.add(target);const end=Date.now()+180000;while(Date.now()<end){if(failure)throw new Error(failure);try{if((await adb(['-s',target,'shell','getprop','sys.boot_completed'])).trim()==='1'){serial=target;return {serial}}}catch{}await new Promise(r=>setTimeout(r,1500))}throw new Error('Démarrage non terminé après 3 minutes. Vérifier virtualisation, accélération et mémoire ; actualiser pour reconnecter.\n'+emulatorLog);}finally{busy=false}});
 on('connect',async p=>{await video.stop();serial=String(p.serial);await device();return {serial};});
 on('install',async()=>{await device();if(!selected)throw new Error('Sélectionner un APK.');const current=await inspect(selected.stagedFile);if(current.hash!==selected.hash)throw new Error('Le fichier APK a changé : le sélectionner à nouveau.');const supported=(await adb(['-s',serial,'shell','getprop','ro.product.cpu.abilist'])).trim().split(',');const native=[...selected.abis.matchAll(/'([^']+)'/g)].map(m=>m[1]);if(native.length&&!native.some(abi=>supported.includes(abi)))throw new Error('Architecture incompatible : APK '+native.join(', ')+' ; appareil '+supported.join(', '));const api=Number((await adb(['-s',serial,'shell','getprop','ro.build.version.sdk'])).trim());if(Number(selected.minApi)>api)throw new Error('API Android '+api+' insuffisante : APK exige '+selected.minApi);const result=await run(tool('platform-tools/adb.exe'),['-s',serial,'install','-r',selected.stagedFile],120000);if(!/Success/.test(result))throw new Error(result);packageName=selected.package;const featureText=await adb(['-s',serial,'shell','pm','list','features']);const missing=selected.requiredFeatures.filter(feature=>!featureText.includes('feature:'+feature));return {message:result+(missing.length?'\nFonctions matérielles à vérifier : '+missing.join(', '):''),package:packageName,warnings:missing};});
 async function launchCurrent(){await device();if(!packageName)throw new Error('Installer l’APK sélectionné avant de lancer.');let component='';for(const category of ['android.intent.category.LEANBACK_LAUNCHER','android.intent.category.LAUNCHER']){const r=await adb(['-s',serial,'shell','cmd','package','resolve-activity','--brief','-a','android.intent.action.MAIN','-c',category,packageName]);component=r.split(/\r?\n/).find(s=>/^[\w.$]+\/[\w.$]+$/.test(s.trim()))?.trim()||'';if(component)break}if(!component)throw new Error('Aucune activité téléphone/TV lançable.');const result=await adb(['-s',serial,'shell','am','start','-W','-n',component]);if(/Error:|Exception/.test(result))throw new Error(result);return {message:result};}
 on('launch',launchCurrent);
 on('installed',async()=>{await device();const output=await adb(['-s',serial,'shell','pm','list','packages','-3']);return {packages:output.split(/\r?\n/).filter(v=>v.startsWith('package:')).map(v=>v.slice(8).trim())}});
 on('launch-installed',async p=>{await device();if(typeof p.package!=='string'||!/^\w+(?:\.\w+)+$/.test(p.package))throw new Error('Package invalide');const list=await adb(['-s',serial,'shell','pm','list','packages','-3']);if(!list.split(/\r?\n/).some(v=>v.trim()==='package:'+p.package))throw new Error('Application absente de cet appareil');packageName=p.package;return await launchCurrent()});
 const keys={up:19,down:20,left:21,right:22,ok:23,back:4,home:3,menu:82,play:85,volumeUp:24,volumeDown:25};
 on('geometry',async()=>{await device();const result=await require('./phone-source.cjs').readGeometry(tool('platform-tools/adb.exe'),serial);onGeometry?.(result.profile);return result;});
 on('key',async p=>{await device();if(!Object.hasOwn(keys,p.key))throw new Error('Touche invalide');await adb(['-s',serial,'shell','input','keyevent',String(keys[p.key])]);return {};});
 on('pointer',async p=>{await device();const vals=[p.x,p.y,...(p.kind==='swipe'?[p.x2,p.y2]:[])];if(!vals.every(n=>Number.isInteger(n)&&n>=0&&n<=8192)||!['tap','swipe'].includes(p.kind))throw new Error('Coordonnées invalides');await adb(['-s',serial,'shell','input',p.kind,...vals.map(String),...(p.kind==='swipe'?['350']:[])]);return {};});
 on('text',async p=>{await device();if(typeof p.text!=='string'||! /^[a-zA-Z0-9 .,!?@_+-]{1,200}$/.test(p.text))throw new Error('Saisie limitée aux caractères latins simples, chiffres et ponctuation affichée (200 caractères).');await adb(['-s',serial,'shell','input','text',p.text.replace(/ /g,'%s')]);return {};});
 on('frame',async()=>{await device();const data=await run(tool('platform-tools/adb.exe'),['-s',serial,'exec-out','screencap','-p'],15000,true);if(data.length<24||data.readUInt32BE(0)!==0x89504e47)throw new Error('Capture Android invalide');return {url:'data:image/png;base64,'+data.toString('base64'),width:data.readUInt32BE(16),height:data.readUInt32BE(20)};});
 on('capture',async()=>{await device();const r=await dialog.showSaveDialog({defaultPath:'android-'+Date.now()+'.png',filters:[{name:'Capture PNG',extensions:['png']}]});if(r.canceled)return {canceled:true};const data=await run(tool('platform-tools/adb.exe'),['-s',serial,'exec-out','screencap','-p'],15000,true);fs.writeFileSync(r.filePath,data);return {path:r.filePath};});
 on('logs',async()=>{await device();let pid='';if(packageName)try{pid=(await adb(['-s',serial,'shell','pidof',packageName])).trim().split(/\s+/)[0]}catch{}const errors=await adb(['-s',serial,'logcat','-d','-t','250',...(/^\d+$/.test(pid)?['--pid='+pid]:[]),'*:E']);return {message:(/^\d+$/.test(pid)?'Erreurs de '+packageName+' (PID '+pid+') :\n':'Erreurs système / applications :\n')+(errors||'Aucune erreur dans les 250 dernières lignes. Les services Google et le matériel virtuel doivent être vérifiés dans le fonctionnement réel.')};});
 on('video-start',async p=>{await device();if(!['balanced','native'].includes(p.quality))throw new Error('Qualité vidéo invalide');return await video.start(serial,p.quality)});
 on('video-stop',async()=>{await video.stop();return {}});
 on('stop',async()=>{await video.stop();await device();if(!launched.has(serial))throw new Error('Studio ferme uniquement les émulateurs démarrés ici.');await adb(['-s',serial,'emu','kill']);launched.delete(serial);serial='';return {};});
 return {stopVideo:()=>video.stop(),selectApk:async file=>{if(mutationBusy)throw new Error('Une opération Android est déjà en cours. Attendre sa fin.');mutationBusy=true;try{return await selectApk(file)}finally{mutationBusy=false}}};
}
module.exports={register,run,diagnose,PROFILES};
