'use strict';
const net=require('net'),fs=require('fs'),path=require('path'),crypto=require('crypto');const {spawn}=require('child_process');
const VERSION='3.3.4',SHA256='8588238c9a5a00aa542906b6ec7e6d5541d9ffb9b5d0f6e1bc0e365e2303079e';
class PacketParser{
 constructor(onPacket){this.buffer=Buffer.alloc(0);this.onPacket=onPacket}
 push(chunk){if(this.buffer.length+chunk.length>8*1024*1024)throw Error('Flux vidéo trop volumineux');this.buffer=Buffer.concat([this.buffer,chunk]);while(this.buffer.length>=12){const size=this.buffer.readUInt32BE(8);if(size===0||size>4*1024*1024)throw Error('Paquet vidéo invalide');if(this.buffer.length<12+size)return;const flags=this.buffer.readBigUInt64BE(0),data=Buffer.from(this.buffer.subarray(12,12+size));this.buffer=this.buffer.subarray(12+size);this.onPacket({config:!!(flags&(1n<<63n)),key:!!(flags&(1n<<62n)),timestamp:Number(flags&((1n<<62n)-1n)),data});}}
}
class AndroidVideo{
 constructor({adb,adbPath,window}){this.adb=adb;this.adbPath=adbPath;this.window=window;this.session=null}
 emit(channel,payload){const w=this.window();if(w&&!w.isDestroyed())w.webContents.send(channel,payload)}
 ack(id,sequence){const s=this.session;if(s&&s.id===id)s.pending.delete(sequence)}
 async stop(){const s=this.session;this.session=null;if(!s)return;s.closed=true;s.socket?.destroy();s.child?.kill();if(s.port)try{await this.adb(['-s',s.serial,'forward','--remove','tcp:'+s.port])}catch{}this.emit('android:video-state',{id:s.id,state:'stopped'});}
 async start(serial,quality){await this.stop();const file=path.join(path.basename(__dirname)==='app.asar'?path.join(process.resourcesPath,'app.asar.unpacked'):__dirname,'vendor','scrcpy-server-v'+VERSION);if(!fs.existsSync(file)||crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex')!==SHA256)throw Error('Serveur vidéo absent ou empreinte invalide. Réinstaller Studio.');const id=crypto.randomBytes(4).readUInt32BE(0)&0x7fffffff,scid=id.toString(16).padStart(8,'0'),remote='/data/local/tmp/ais-scrcpy-'+scid+'.jar';const s={id,serial,pending:new Set(),sequence:0,closed:false,waitingKey:false,logs:''};this.session=s;
 try{await this.adb(['-s',serial,'push',file,remote]);if(s.closed)throw Error('Vidéo annulée');const out=await this.adb(['-s',serial,'forward','tcp:0','localabstract:scrcpy_'+scid]);s.port=Number(out.trim());if(s.closed){if(Number.isInteger(s.port))await this.adb(['-s',serial,'forward','--remove','tcp:'+s.port]);throw Error('Vidéo annulée')}if(!Number.isInteger(s.port)||s.port<1024||s.port>65535)throw Error('Port vidéo invalide');const settings=quality==='native'?{size:0,bitrate:12000000,fps:60}:{size:1920,bitrate:8000000,fps:30};
 s.child=spawn(this.adbPath(),['-s',serial,'shell','CLASSPATH='+remote,'app_process','/','com.genymobile.scrcpy.Server',VERSION,'scid='+scid,'tunnel_forward=true','audio=false','control=false','cleanup=true','send_device_meta=false','send_dummy_byte=false','send_codec_meta=false','send_frame_meta=true','video_codec=h264','max_size='+settings.size,'video_bit_rate='+settings.bitrate,'max_fps='+settings.fps,'video_codec_options=i-frame-interval=1'],{shell:false,windowsHide:true,stdio:['ignore','pipe','pipe']});
 const log=data=>{s.logs=(s.logs+data.toString()).slice(-8000)};s.child.stdout.on('data',log);s.child.stderr.on('data',log);s.child.on('error',e=>{s.error=e.message});s.child.on('exit',code=>{s.error='Serveur vidéo arrêté ('+code+'). '+s.logs;if(!s.closed)this.emit('android:video-state',{id,state:'error',error:s.error})});
 const startTime=Date.now();let first=false;while(!first&&Date.now()-startTime<20000){if(s.closed||this.session!==s)throw Error('Vidéo annulée');if(s.error)throw Error(s.error);first=await new Promise(resolve=>{const socket=net.createConnection({host:'127.0.0.1',port:s.port});s.socket=socket;let settled=false;const settle=value=>{if(settled)return;settled=true;clearTimeout(timer);resolve(value)};const parser=new PacketParser(packet=>{settle(true);if(s.closed||this.session!==s)return;if(packet.config){s.config=packet;}else if(s.pending.size>=8){s.waitingKey=true;return}else if(s.waitingKey&&!packet.key)return;else if(packet.key)s.waitingKey=false;const sequence=++s.sequence;s.pending.add(sequence);this.emit('android:video-packet',{id,sequence,...packet});});const timer=setTimeout(()=>{socket.destroy();settle(false)},1000);socket.on('data',chunk=>{try{parser.push(chunk)}catch(e){s.error=e.message;socket.destroy();this.emit('android:video-state',{id,state:'error',error:e.message})}});socket.on('error',()=>settle(false));socket.on('close',()=>{settle(false);if(first&&!s.closed&&this.session===s)this.emit('android:video-state',{id,state:'error',error:'Flux vidéo interrompu. '+s.logs})});});if(!first)await new Promise(r=>setTimeout(r,200));}
 if(!first)throw Error('Vidéo Android indisponible après 20 secondes. '+s.logs);return {id,codec:'H.264',maxFps:settings.fps,maxSize:settings.size};
 }catch(e){if(this.session===s)await this.stop();throw e}
 }
}
module.exports={AndroidVideo,PacketParser,VERSION,SHA256};
