const fs=require('fs'),path=require('path'),crypto=require('crypto'),{execFile}=require('child_process'),yauzl=require('yauzl');
const digest=s=>crypto.createHash('sha256').update(s).digest('hex');
async function fileDigest(file){const h=crypto.createHash('sha256');for await(const chunk of fs.createReadStream(file))h.update(chunk);return h.digest('hex')}
function run(file,args,env=process.env,cwd){return new Promise((resolve,reject)=>execFile(file,args,{env,cwd,shell:false,windowsHide:true,timeout:300000,maxBuffer:16*1024*1024},(e,out,err)=>e?reject(Error(String(err||out||e.message).slice(-12000))):resolve(String(out)+String(err))))}
async function withBuildPath(directory,action){
 if(process.platform!=='win32'||!/[^\x00-\x7f]/.test(directory))return action(directory);
 const subst=path.join(process.env.SystemRoot||'C:\\Windows','System32','subst.exe');
 for(let code=90;code>=68;code--){const drive=String.fromCharCode(code)+':';if(fs.existsSync(drive+'\\'))continue;try{await run(subst,[drive,directory])}catch{continue}try{return await action(drive+'\\')}finally{await run(subst,[drive,'/D'])}}
 throw Error('Aucun lecteur temporaire disponible pour reconstruire un APK dans un chemin contenant des caractères internationaux.');
}
function checkZip(file){return new Promise((resolve,reject)=>yauzl.open(file,{lazyEntries:true},(error,zip)=>{if(error)return reject(error);let size=0,count=0;const names=new Set();zip.on('error',reject);zip.on('entry',e=>{const n=e.fileName.replaceAll('\\','/');size+=e.uncompressedSize;if(((e.externalFileAttributes>>>16)&0xf000)===0xa000||names.has(n.toLowerCase())||n.startsWith('/')||n.includes(':')||n.split('/').includes('..')||++count>60000||size>3*1024**3){zip.close();return reject(Error('Archive APK invalide ou trop volumineuse.'))}names.add(n.toLowerCase());zip.readEntry()});zip.on('end',resolve);zip.readEntry()}))}
function create({app,dialog}){
const base=path.join(app.getPath('userData'),'apk-editor'),settings=path.join(base,'tools.json');fs.mkdirSync(base,{recursive:true});let config={};try{config=JSON.parse(fs.readFileSync(settings))}catch{}let busy=false;const projects=new Map();
function detectedTools(){
 const runtime=app.isPackaged?path.join(process.resourcesPath,'apk-runtime'):path.join(__dirname,'runtime');
 const bundledJava=path.join(runtime,'java','bin','java.exe'),bundledSdk=path.join(runtime,'sdk');
 const javaCandidates=[bundledJava,config.java,...[process.env.JAVA_HOME,process.env.JDK_HOME].filter(Boolean).map(h=>path.join(h,'bin','java.exe'))];
 const java=javaCandidates.find(j=>{if(typeof j!=='string'||!fs.existsSync(j)||!fs.existsSync(path.join(path.dirname(j),'keytool.exe')))return false;try{const release=fs.readFileSync(path.join(path.dirname(j),'..','release'),'utf8');return Number((release.match(/JAVA_VERSION="(\d+)/)||[])[1])>=17}catch{return false}});
 const sdkCandidates=[bundledSdk,config.sdk,process.env.ANDROID_SDK_ROOT,process.env.ANDROID_HOME];try{sdkCandidates.push(JSON.parse(fs.readFileSync(path.join(app.getPath('userData'),'android-lab.json'),'utf8')).sdk)}catch{}
 const sdk=sdkCandidates.find(s=>typeof s==='string'&&fs.existsSync(path.join(s,'build-tools')));
 if(java&&sdk&&(config.java!==java||config.sdk!==sdk)){config.java=java;config.sdk=sdk;fs.writeFileSync(settings,JSON.stringify(config))}
 return {java,sdk};
}
function tools(){const detected=detectedTools();let sdk=detected.sdk||config.sdk||process.env.ANDROID_SDK_ROOT||process.env.ANDROID_HOME;try{sdk=sdk||JSON.parse(fs.readFileSync(path.join(app.getPath('userData'),'android-lab.json'))).sdk}catch{}const java=detected.java;if(!java||!fs.existsSync(java))throw Error('Configurer Java 17 ou plus dans « Outils APK ».');if(!sdk||!fs.existsSync(path.join(sdk,'build-tools')))throw Error('Configurer le SDK Android avec Build-Tools dans « Outils APK ».');const version=fs.readdirSync(path.join(sdk,'build-tools')).sort((a,b)=>b.localeCompare(a,undefined,{numeric:true})).find(v=>fs.existsSync(path.join(sdk,'build-tools',v,'lib','apksigner.jar')));if(!version)throw Error('Android SDK Build-Tools avec apksigner absent.');const jar=path.join(__dirname,'vendor','apktool','apktool.jar').replace('app.asar'+path.sep,'app.asar.unpacked'+path.sep);if(digest(fs.readFileSync(jar))!=='dbf930b076c6b9be08d57c449cacefc3bdd6b71ebd59b3066fc0e1f5b14f9423')throw Error('Intégrité Apktool invalide.');return {java,sdk,jar,build:path.join(sdk,'build-tools',version)}}
function project(id){if(!/^[a-f0-9-]{36}$/.test(id||''))throw Error('Projet APK invalide.');if(projects.has(id))return projects.get(id);const dir=path.join(base,id),meta=JSON.parse(fs.readFileSync(path.join(dir,'project.json')));const p={...meta,id,dir,decoded:path.join(dir,'decoded')};projects.set(id,p);return p}
function file(p,name){if(typeof name!=='string'||name.includes('\\')||name.includes(':')||name.startsWith('/')||name.split('/').includes('..')||!(/^(assets|res|smali[^/]*)\//.test(name)||name==='AndroidManifest.xml'))throw Error('Chemin APK refusé.');const real=fs.realpathSync(path.join(p.decoded,...name.split('/')));if(!real.startsWith(fs.realpathSync(p.decoded)+path.sep))throw Error('Chemin APK hors projet.');return real}
const guarded=async fn=>{if(busy)throw Error('Une opération APK est déjà en cours.');busy=true;try{return await fn()}finally{busy=false}};
async function importApk(input){return guarded(async()=>{const t=tools(),original=fs.realpathSync(input);if(path.extname(original).toLowerCase()!=='.apk'||fs.statSync(original).size>2*1024**3)throw Error('Choisir un APK autonome de moins de 2 Go.');await checkZip(original);const id=crypto.randomUUID(),dir=path.join(base,id),decoded=path.join(dir,'decoded');fs.mkdirSync(dir);const copy=path.join(dir,'original.apk');fs.copyFileSync(original,copy);const info=await run(path.join(t.build,'aapt.exe'),['dump','badging','original.apk'],undefined,dir);if(/uses-split:|split='[^']+'/.test(info))throw Error('APK fractionné : fournir un APK autonome complet.');const pkg=(info.match(/package: name='([^']+)'/)||[])[1];if(!pkg)throw Error('Package APK invalide.');const cert=await run(t.java,['-jar',path.join(t.build,'lib','apksigner.jar'),'verify','--print-certs',copy]);await run(t.java,['-jar',t.jar,'d',copy,'-o',decoded,'-p',path.join(dir,'framework')]);const p={id,dir,decoded,original,package:pkg,label:path.basename(original),originalHash:await fileDigest(copy),originalCertificate:(cert.match(/certificate SHA-256 digest: (\w+)/)||[])[1]||''};fs.writeFileSync(path.join(dir,'project.json'),JSON.stringify(p,null,2));projects.set(id,p);return p})}
function list(id){const p=project(id),out=[];function walk(dir){for(const e of fs.readdirSync(dir,{withFileTypes:true})){if(e.isSymbolicLink())continue;const f=path.join(dir,e.name);if(e.isDirectory())walk(f);else {const name=path.relative(p.decoded,f).split(path.sep).join('/');if((/^(assets|res|smali[^/]*)\//.test(name)||name==='AndroidManifest.xml')&&out.length<20000)out.push({name,size:fs.statSync(f).size,text:/\.(xml|smali|html?|css|js|json|txt|svg)$/i.test(name),image:/\.(png|jpe?g|webp)$/i.test(name)})}}}walk(p.decoded);return out}
async function exportApk(id,key={}){return guarded(async()=>{const p=project(id),t=tools();const chosen=await dialog.showSaveDialog({title:'Exporter l’APK modifié et signé',defaultPath:p.label.replace(/\.apk$/i,'-modifie.apk'),filters:[{name:'APK Android',extensions:['apk']}]});if(chosen.canceled)return {canceled:true};const output=path.resolve(/\.apk$/i.test(chosen.filePath)?chosen.filePath:chosen.filePath+'.apk');if(output.toLowerCase()===p.original.toLowerCase()||output.toLowerCase().startsWith(p.dir.toLowerCase()+path.sep))throw Error('Exporter vers un autre fichier que l’APK original et le projet de travail.');let ks=config.keystore,pass=config.password,alias='studio';if(key.original===true){if(!config.originalKeystore)throw Error('Choisir votre clé de signature originale.');ks=config.originalKeystore;pass=String(key.password||'');alias=String(key.alias||'');if(!alias)throw Error('Indiquer l’alias de votre clé.')}else if(!ks){ks=path.join(base,'studio-signing.jks');pass=crypto.randomBytes(24).toString('hex');await run(path.join(path.dirname(t.java),'keytool.exe'),['-genkeypair','-keystore',ks,'-storepass:env','AIS_APK_PASS','-keypass:env','AIS_APK_PASS','-alias',alias,'-keyalg','RSA','-keysize','2048','-validity','10000','-dname','CN=App Interface Studio'],{...process.env,AIS_APK_PASS:pass});config.keystore=ks;config.password=pass;fs.writeFileSync(settings,JSON.stringify(config));}
const build=path.join(p.dir,'build-'+crypto.randomUUID());fs.mkdirSync(build);const snapshot=path.join(build,'input');fs.cpSync(p.decoded,snapshot,{recursive:true,filter:f=>!['build','dist'].includes(path.basename(f))});const unsigned=path.join(build,'unsigned.apk'),aligned=path.join(build,'aligned.apk'),signed=path.join(build,'signed.apk');await withBuildPath(build,async buildRoot=>{const framework=path.join(buildRoot,'framework'),temp=path.join(buildRoot,'temp');fs.mkdirSync(temp,{recursive:true});if(fs.existsSync(path.join(p.dir,'framework')))fs.cpSync(path.join(p.dir,'framework'),framework,{recursive:true});await run(t.java,['-Djava.io.tmpdir='+temp,'-jar',t.jar,'b',path.join(buildRoot,'input'),'-f','-p',framework,'-o',path.join(buildRoot,'unsigned.apk')],undefined,buildRoot)});await run(path.join(t.build,'zipalign.exe'),['-P','16','-f','4','unsigned.apk','aligned.apk'],undefined,build);await run(t.java,['-jar',path.join(t.build,'lib','apksigner.jar'),'sign','--ks',ks,'--ks-key-alias',alias,'--ks-pass','env:AIS_APK_PASS','--key-pass','env:AIS_APK_KEY_PASS','--out',signed,aligned],{...process.env,AIS_APK_PASS:pass,AIS_APK_KEY_PASS:key.original===true?String(key.keyPassword||pass):pass});const verified=await run(t.java,['-jar',path.join(t.build,'lib','apksigner.jar'),'verify','--verbose','--print-certs',signed]);await run(path.join(t.build,'zipalign.exe'),['-c','-P','16','4','signed.apk'],undefined,build);const certificate=(verified.match(/certificate SHA-256 digest: (\w+)/)||[])[1]||'';if(!certificate)throw Error('Certificat de l’APK signé introuvable.');const temp=output+'.'+crypto.randomUUID()+'.tmp';await fs.promises.copyFile(signed,temp);await fs.promises.rename(temp,output);p.lastExport=output;fs.writeFileSync(path.join(p.dir,'project.json'),JSON.stringify(p,null,2));return {path:output,package:p.package,sameSignature:certificate===p.originalCertificate,certificate,sha256:await fileDigest(output),verified:true}})}
return {importApk,project,list,exportApk,tools,async command(action,p={}){
if(action==='status'){const t=tools();return {ready:true,java:t.java,sdk:t.sdk,apktool:'3.0.3'}}
if(action==='tools'){const r=await dialog.showOpenDialog({title:'Choisir java.exe (Java 17 ou plus)',properties:['openFile'],filters:[{name:'Java',extensions:['exe']}]});if(r.canceled)return {canceled:true};if(path.basename(r.filePaths[0]).toLowerCase()!=='java.exe')throw Error('Choisir java.exe.');const sdk=await dialog.showOpenDialog({title:'Choisir le SDK Android',properties:['openDirectory']});if(sdk.canceled)return {canceled:true};config.java=fs.realpathSync(r.filePaths[0]);config.sdk=fs.realpathSync(sdk.filePaths[0]);fs.writeFileSync(settings,JSON.stringify(config));return {configured:true}}
if(action==='key'){const r=await dialog.showOpenDialog({title:'Choisir votre clé de signature originale',properties:['openFile'],filters:[{name:'Keystore',extensions:['jks','keystore','p12']}]});if(!r.canceled){config.originalKeystore=fs.realpathSync(r.filePaths[0]);fs.writeFileSync(settings,JSON.stringify(config))}return {canceled:r.canceled}}
if(action==='list')return {files:list(p.id)};
if(action==='read'){const f=file(project(p.id),p.name);if(fs.statSync(f).size>2*1024*1024||!list(p.id).find(v=>v.name===p.name)?.text)throw Error('Fichier texte non éditable (limite 2 Mo).');const content=fs.readFileSync(f,'utf8');return {content,hash:digest(content)}}
if(action==='save')return guarded(async()=>{const f=file(project(p.id),p.name);if(typeof p.content!=='string'||Buffer.byteLength(p.content)>2*1024*1024||!list(p.id).find(v=>v.name===p.name)?.text)throw Error('Contenu texte invalide.');if(digest(fs.readFileSync(f,'utf8'))!==p.hash)throw Error('Ce fichier a changé. Le rouvrir avant de sauvegarder.');fs.copyFileSync(f,path.join(project(p.id).dir,'backup-'+crypto.randomUUID()));fs.writeFileSync(f,p.content);return {hash:digest(p.content)}});
if(action==='image')return guarded(async()=>{const f=file(project(p.id),p.name);if(!/\.(png|jpe?g|webp)$/i.test(f))throw Error('Sélectionner une image.');const r=await dialog.showOpenDialog({title:'Remplacer cette image',properties:['openFile'],filters:[{name:'Image de même format',extensions:[path.extname(f).slice(1)]}]});if(r.canceled)return {canceled:true};if(path.extname(r.filePaths[0]).toLowerCase()!==path.extname(f).toLowerCase())throw Error('Le format doit correspondre.');fs.copyFileSync(f,path.join(project(p.id).dir,'backup-'+crypto.randomUUID()));fs.copyFileSync(r.filePaths[0],f);return {saved:true}});
if(action==='export')return exportApk(p.id,p.key);if(action==='project')return {project:project(p.id)};throw Error('Action APK invalide.')}}}
module.exports={create,checkZip};
