const fs=require('fs'),path=require('path');
function register({app,ipcMain,BrowserWindow,WebContentsView,shell,screen,getWindow,getWebRoot}){
 let view=null,host=null,floating=null,lastBounds=null;const settings=path.join(app.getPath('userData'),'chatgpt-window.json');
 try{lastBounds=JSON.parse(fs.readFileSync(settings,'utf8'));}catch{}
 function detach(){if(view&&host&&!host.isDestroyed())host.contentView.removeChildView(view);host=null;}
 function place(w,b){detach();if(!view||!b)return;const [width,height]=w.getContentSize();if(![b.x,b.y,b.width,b.height].every(Number.isFinite))return;const x=Math.max(0,Math.round(b.x)),y=Math.max(0,Math.round(b.y)),right=Math.min(width,Math.round(b.x+b.width)),bottom=Math.min(height,Math.round(b.y+b.height));if(right<=x||bottom<=y)return;view.setBounds({x,y,width:right-x,height:bottom-y});w.contentView.addChildView(view);host=w;}
 function emit(){const w=getWindow();if(w&&!w.isDestroyed())w.webContents.send('chatgpt:float-state',{floating:!!floating,size:floating?.getContentSize()});}
 function ensureView(){if(view)return;const w=getWindow();view=new WebContentsView({webPreferences:{partition:'persist:studio-chatgpt',contextIsolation:true,nodeIntegration:false,sandbox:true}});view.webContents.session.setPermissionRequestHandler((_w,_p,callback)=>callback(false));view.webContents.setWindowOpenHandler(({url})=>{if(!url.startsWith('https://'))return {action:'deny'};return {action:'allow',overrideBrowserWindowOptions:{webPreferences:{partition:'persist:studio-chatgpt',contextIsolation:true,nodeIntegration:false,sandbox:true}}}});view.webContents.loadURL('https://chatgpt.com/').catch(error=>w?.webContents.send('chatgpt:web-status',{error:'ChatGPT ne se charge pas. Utilisez Navigateur. '+error.message}));w.once('closed',()=>{floating?.destroy();floating=null;detach();view?.webContents.close();view=null;});}
 async function openFloating(size={}){if(floating){floating.focus();emit();return;}const area=screen.getDisplayMatching(getWindow().getBounds()).workArea,b=lastBounds||{};const width=Math.min(area.width,Math.max(420,b.width||Number(size.width)||680)),height=Math.min(area.height,Math.max(380,b.height||Number(size.height)||850));floating=new BrowserWindow({title:'ChatGPT · édition flottante',width,height,useContentSize:true,minWidth:420,minHeight:380,resizable:true,maximizable:true,autoHideMenuBar:true,webPreferences:{preload:path.join(__dirname,'studio-chat-float-preload.cjs'),contextIsolation:true,nodeIntegration:false,sandbox:true}});floating.webContents.setWindowOpenHandler(()=>({action:'deny'}));floating.webContents.on('will-navigate',e=>e.preventDefault());const w=floating;const remember=()=>{if(w.isDestroyed())return;lastBounds=w.getContentBounds();try{fs.mkdirSync(path.dirname(settings),{recursive:true});fs.writeFileSync(settings,JSON.stringify(lastBounds));}catch{}emit();};const parent=getWindow(),parentClosed=()=>{if(host===w)detach();w.destroy();};parent.once('closed',parentClosed);w.on('closed',()=>parent.removeListener('closed',parentClosed));w.on('close',()=>{if(host===w)detach();});w.on('resize',remember);w.on('move',remember);w.on('closed',()=>{if(host===w)host=null;floating=null;emit();});await w.loadFile(path.join(getWebRoot(),'studio-chat-floating.html'));emit();}
 ipcMain.handle('chatgpt:floating-command',async(e,p={})=>{if(!floating||e.sender!==floating.webContents||e.senderFrame!==e.sender.mainFrame)return {ok:false,error:'Origine refusée.'};try{if(p.action==='view-bounds'){if(view)place(floating,p.bounds);return {ok:true};}if(!['snapshot','interact','fields'].includes(p.action))throw Error('Commande inconnue.');const w=getWindow();const snapshot=await w.webContents.executeJavaScript('window.StudioChatGpt.floatingCommand('+JSON.stringify(p)+')');return {ok:true,snapshot};}catch(error){return {ok:false,error:error.message};}});
 ipcMain.handle('chatgpt:view',async(e,p={})=>{const w=getWindow();if(e.sender!==w?.webContents||e.senderFrame!==e.sender.mainFrame)return {ok:false,error:'Origine refusée.'};try{
  if(p.action==='state')return {ok:true,floating:!!floating,size:floating?.getContentSize()};
  if(p.action==='external'){await shell.openExternal('https://chatgpt.com/');return {ok:true};}
  if(p.action==='float'){detach();await openFloating(p.size);return {ok:true};}
  if(p.action==='dock'){detach();floating?.close();return {ok:true};}
  if(p.action==='size'){if(!floating)return {ok:true};const size=p.size||{};if(![size.width,size.height].every(Number.isFinite)||size.width<420||size.height<380||size.width>4000||size.height>3000)throw Error('Taille invalide.');floating.setContentSize(Math.round(size.width),Math.round(size.height));return {ok:true};}
  if(p.action==='close'){detach();floating?.close();return {ok:true};}
  if(!['open','bounds'].includes(p.action))throw Error('Commande inconnue.');ensureView();if(!floating)place(w,p.bounds);return {ok:true};
 }catch(error){return {ok:false,error:error.message};}});
 async function smoke(){const w=getWindow();const before=await w.webContents.executeJavaScript("(() => {const p=document.querySelector('.studio-chat-panel');p.hidden=false;document.getElementById('studioChatWidth').value='900';document.getElementById('studioChatHeight').value='650';document.getElementById('studioChatSize').click();return {width:p.getBoundingClientRect().width,height:p.getBoundingClientRect().height};})()");if(before.width!==900||before.height!==650)throw Error('Taille du panneau intégré incorrecte.');await openFloating({width:680,height:700});const r=await floating.webContents.executeJavaScript("window.StudioFloatingChat.command({action:'fields',fields:[{id:'studioChatPrompt',value:'Demande conservée dans la fenêtre flottante'}]})");if(!r.ok||!r.snapshot.fields.some(f=>f.id==='studioChatPrompt'&&f.value==='Demande conservée dans la fenêtre flottante'))throw Error('État du panneau flottant perdu.');floating.setContentSize(850,650);const size=floating.getContentSize();if(size[0]!==850||size[1]!==650)throw Error('Fenêtre flottante non redimensionnable.');const child=floating;await new Promise(resolve=>{child.once('closed',resolve);child.close();});const after=await w.webContents.executeJavaScript("document.getElementById('studioChatPrompt').value");if(after!=='Demande conservée dans la fenêtre flottante')throw Error('Réintégration : demande perdue.');return {ok:true,embeddedSize:true,nativeFloating:true,resize:true,sharedState:true,redock:true};}
 return {detach,smoke};
}
module.exports={register};
