// Official ChatGPT plan OAuth. Credentials stay in the Windows user profile.
const fs=require('fs'),path=require('path'),crypto=require('crypto'),http=require('http');
const AUTH='https://auth.openai.com',API='https://api.openai.com/v1',random=()=>crypto.randomBytes(32).toString('base64url');
async function json(url,options={}){const r=await fetch(url,{...options,redirect:'error',signal:options.signal||AbortSignal.timeout(30000)});if(!r.ok)throw Error('OpenAI : requête refusée ('+r.status+').');return r.json()}
async function identity(token,client,nonce){const parts=String(token).split('.');if(parts.length!==3)throw Error('Identité invalide.');const header=JSON.parse(Buffer.from(parts[0],'base64url')),claims=JSON.parse(Buffer.from(parts[1],'base64url'));if(header.alg!=='RS256')throw Error('Signature non prise en charge.');const keys=await json(AUTH+'/.well-known/jwks.json'),key=keys.keys.find(k=>k.kid===header.kid&&k.kty==='RSA');if(!key||!crypto.verify('RSA-SHA256',Buffer.from(parts[0]+'.'+parts[1]),crypto.createPublicKey({key,format:'jwk'}),Buffer.from(parts[2],'base64url')))throw Error('Signature invalide.');if(claims.iss!==AUTH||!(Array.isArray(claims.aud)?claims.aud:[claims.aud]).includes(client)||!claims.sub||!Number.isFinite(claims.exp)||claims.exp<Date.now()/1000-5||claims.nonce!==nonce)throw Error('Identité expirée ou incorrecte.');return claims}
async function responseText(body){let buffer='',output='',completed=false;const decoder=new TextDecoder();for await(const chunk of body){buffer+=decoder.decode(chunk,{stream:true}).replace(/\r\n/g,'\n');let end;while((end=buffer.indexOf('\n\n'))>=0){const block=buffer.slice(0,end);buffer=buffer.slice(end+2);const data=block.split('\n').filter(l=>l.startsWith('data:')).map(l=>l.slice(5).trim()).join('\n');if(!data||data==='[DONE]')continue;const event=JSON.parse(data);if(event.type==='response.output_text.delta')output+=event.delta;if(event.type==='response.completed')completed=true;if(['response.failed','response.incomplete','error'].includes(event.type))throw Error('Réponse IA interrompue. Aucun changement appliqué.');if(output.length>4*1024*1024)throw Error('Réponse trop volumineuse.')}}if(!completed)throw Error('Réponse incomplète. Aucun changement appliqué.');return output}
function create({app,safeStorage,shell,notify=()=>{}}){const dir=path.join(app.getPath('userData'),'chatgpt-direct');fs.mkdirSync(dir,{recursive:true});const hostFile=path.join(dir,'host.json'),record=path.join(dir,'account.enc');let host;try{host=JSON.parse(fs.readFileSync(hostFile)).id}catch{host='urn:uuid:'+crypto.randomUUID();fs.writeFileSync(hostFile,JSON.stringify({id:host}))}let account=null,pending=null;function save(){if(!safeStorage.isEncryptionAvailable())throw Error('Protection Windows des identifiants indisponible.');const tmp=record+'.tmp';fs.writeFileSync(tmp,safeStorage.encryptString(JSON.stringify(account)));fs.renameSync(tmp,record)}function load(){try{if(fs.existsSync(record)&&safeStorage.isEncryptionAvailable())account=JSON.parse(safeStorage.decryptString(fs.readFileSync(record)))}catch{}}if(app.whenReady)app.whenReady().then(load);else load();app.on?.('before-quit',()=>{if(pending){clearTimeout(pending.timer);pending.server.close();pending=null}});
const status=()=>({ok:true,connected:!!account?.access_token,email:account?.email||'',plan:!!account?.scope?.split(' ').includes('chatgpt.tokens.use.direct'),pending:!!pending});
async function login(){if(pending)throw Error('Connexion déjà en cours.');if(!safeStorage.isEncryptionAvailable())throw Error('Protection Windows des identifiants indisponible.');const state=random(),nonce=random(),verifier=random(),saved=account;const server=http.createServer(async(req,res)=>{const u=new URL(req.url,'http://127.0.0.1');if(u.pathname!=='/auth/callback'||u.searchParams.get('state')!==state){res.writeHead(400);res.end('Invalid callback');return}if(!pending){res.writeHead(410);res.end();return}pending=null;clearTimeout(timer);server.close();try{if(u.searchParams.get('error'))throw Error('Connexion annulée.');const client=u.searchParams.get('client_id')||saved?.client_id;if(!client||client==='dynamic_agent_client'||(saved&&client!==saved.client_id))throw Error('Enregistrement incomplet.');account={...saved,client_id:client};save();const tokens=await json(AUTH+'/api/accounts/oauth/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({grant_type:'authorization_code',client_id:client,code:u.searchParams.get('code')||'',code_verifier:verifier,redirect_uri:redirect,resource:API})});const claims=await identity(tokens.id_token,client,nonce);if(saved?.subject&&saved.subject!==claims.sub)throw Error('Compte différent. Déconnectez-vous avant de changer de compte.');account={...tokens,client_id:client,subject:claims.sub,email:claims.email||'',expires_at:Date.now()+Number(tokens.expires_in||3600)*1000};save();res.end('Connexion terminee. Vous pouvez revenir dans Studio.');notify(status())}catch(e){account=saved||{client_id:account?.client_id};save();res.writeHead(400);res.end('Connexion impossible. Revenez dans Studio.');notify({ok:false,error:e.message})}});await new Promise((resolve,reject)=>{server.once('error',reject);server.listen(0,'127.0.0.1',resolve)});const redirect='http://127.0.0.1:'+server.address().port+'/auth/callback',timer=setTimeout(()=>{server.close();pending=null;notify({ok:false,error:'Connexion expirée.'})},300000);pending={server,timer};const url=new URL(AUTH+'/api/accounts/authorize');url.search=new URLSearchParams({client_id:saved?.client_id||'dynamic_agent_client',...(!saved?.client_id?{agent_name_hint:'App Interface Studio'}:{}),ext_agent_host_id:host,response_type:'code',redirect_uri:redirect,scope:'openid profile email offline_access resource.invoke chatgpt.tokens.use.direct',resource:API,state,nonce,code_challenge_method:'S256',code_challenge:crypto.createHash('sha256').update(verifier).digest('base64url')});try{await shell.openExternal(url.href)}catch(e){clearTimeout(timer);server.close();pending=null;throw e}return {ok:true,pending:true}}
async function token(){if(!account?.access_token)throw Error('Connectez votre compte ChatGPT.');if(account.expires_at<Date.now()+60000){const fresh=await json(AUTH+'/api/accounts/oauth/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({grant_type:'refresh_token',client_id:account.client_id,refresh_token:account.refresh_token,resource:API})});account={...account,...fresh,expires_at:Date.now()+Number(fresh.expires_in||3600)*1000};save()}if(!status().plan)throw Error('Votre compte n’a pas autorisé l’utilisation du forfait ChatGPT.');return account.access_token}
async function models(){const catalog=await json(API+'/models',{headers:{Authorization:'Bearer '+await token()}});return (catalog.models||[]).filter(m=>m.visibility==='list').map(m=>({slug:m.slug,name:m.display_name}))}
async function infer(content,model,signal){const available=await models();if(!available.some(m=>m.slug===model))throw Error('Modèle indisponible pour ce compte.');const r=await fetch(API+'/responses',{method:'POST',redirect:'error',signal,headers:{Authorization:'Bearer '+await token(),'Content-Type':'application/json'},body:JSON.stringify({model,store:false,stream:true,input:[{role:'user',content}]})});if(!r.ok)throw Error('OpenAI : demande refusée ('+r.status+'). Aucun changement appliqué.');return responseText(r.body)}
function logout(){if(pending){clearTimeout(pending.timer);pending.server.close();pending=null}account=null;if(fs.existsSync(record))fs.unlinkSync(record);return status()}
return {status,login,logout,models,infer};}
module.exports={create,responseText,identity};
