const fs=require('fs'),path=require('path');
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const decode=v=>String(v||'').replace(/&(?:amp|lt|gt|quot|apos);/g,c=>({'&amp;':'&','&lt;':'<','&gt;':'>','&quot;':'"','&apos;':"'"}[c])).replace(/&#(x[\da-f]+|\d+);/gi,(_,n)=>String.fromCodePoint(parseInt(n.replace(/^x/i,''),/^x/i.test(n)?16:10)));
function parse(xml){const root={tag:'root',a:{},children:[]},stack=[root];let index=0;for(const m of xml.matchAll(/<!--[\s\S]*?-->|<\/?[\w.$:-]+\b[^>]*>/g)){const token=m[0];if(token.startsWith('<!--'))continue;if(token.startsWith('</')){if(stack.length>1)stack.pop();continue}const tag=token.match(/^<([\w.$:-]+)/)[1],a={};for(const x of token.matchAll(/([\w:.-]+)\s*=\s*"([^"]*)"/g))a[x[1]]=decode(x[2]);const node={tag,a,children:[],index:index++};stack.at(-1).children.push(node);if(!/\/\s*>$/.test(token))stack.push(node)}return root}
function resources(res){const values=new Map(),styles=new Map();const dir=path.join(res,'values');if(fs.existsSync(dir))for(const e of fs.readdirSync(dir).filter(n=>n.endsWith('.xml'))){const xml=fs.readFileSync(path.join(dir,e),'utf8');for(const m of xml.matchAll(/<(string|color|dimen|bool|integer)\b[^>]*name="([^"]+)"[^>]*>([\s\S]*?)<\/\1>/g))values.set('@'+m[1]+'/'+m[2],decode(m[3]).replace(/\\n/g,'\n'));for(const m of xml.matchAll(/<style\b([^>]*)>([\s\S]*?)<\/style>/g)){const name=m[1].match(/name="([^"]+)"/)?.[1],parent=m[1].match(/parent="([^"]+)"/)?.[1],a={};for(const item of m[2].matchAll(/<item\s+name="([^"]+)"[^>]*>([\s\S]*?)<\/item>/g))a[item[1]]=decode(item[2]);if(name)styles.set('@style/'+name,{parent,a})}}
const value=(v,depth=0)=>depth>8?v:values.has(v)?value(values.get(v),depth+1):v;
const style=(v,depth=0)=>{const s=styles.get(v);return !s||depth>8?{}:{...style(s.parent?.startsWith('@')?s.parent:'@style/'+s.parent,depth+1),...s.a}};
return {value,style}}
function color(v,r){v=r.value(v);const builtins={'@android:color/transparent':'transparent','@android:color/white':'#fff','@android:color/black':'#000'};if(builtins[v])return builtins[v];if(/^#[\da-f]{8}$/i.test(v))return '#'+v.slice(3)+v.slice(1,3);return /^#(?:[\da-f]{3}|[\da-f]{4}|[\da-f]{6})$/i.test(v)?v:null}
function number(v,r,f=0){const n=Number.parseFloat(r.value(v));return Number.isFinite(n)?n:f}
function drawableFile(res,ref){const m=ref?.match(/^@(drawable|mipmap)\/([\w.]+)$/);if(!m)return null;const dirs=fs.readdirSync(res).filter(d=>d===m[1]||d.startsWith(m[1]+'-')).sort((a,b)=>(a===m[1]?-1:b===m[1]?1:0));for(const dir of dirs){const names=fs.readdirSync(path.join(res,dir));const name=names.find(n=>n===m[2]+'.xml')||names.find(n=>n.replace(/(?:\.9)?\.(png|webp|jpe?g)$/i,'')===m[2]);if(name)return path.join(res,dir,name)}return null}
function drawable(res,ref,r,depth=0){if(depth>8)return {};const c=color(ref,r);if(c)return {css:'background:'+c+';'};const file=drawableFile(res,ref);if(!file)return {};if(!file.endsWith('.xml')){const ext=path.extname(file).slice(1).replace('jpg','jpeg');return {src:'data:image/'+ext+';base64,'+fs.readFileSync(file).toString('base64')}}let n=parse(fs.readFileSync(file,'utf8')).children[0];if(n.tag==='selector'){n=(n.children.find(c=>c.tag==='item'&&!Object.keys(c.a).some(k=>k.startsWith('android:state_')))||n.children.at(-1));if(n?.a['android:drawable'])return drawable(res,n.a['android:drawable'],r,depth+1);n=n?.children[0]}if(!n)return {};
if(n.tag==='vector'){const svgNode=n=>{if(n.tag==='path'){const a=n.a;return '<path d="'+esc(a['android:pathData'])+'" fill="'+esc(color(a['android:fillColor'],r)||'none')+'" fill-opacity="'+number(a['android:fillAlpha'],r,1)+'" stroke="'+esc(color(a['android:strokeColor'],r)||'none')+'" stroke-width="'+number(a['android:strokeWidth'],r)+'" stroke-linecap="'+esc(a['android:strokeLineCap']||'butt')+'"/>'}if(n.tag==='group'){const a=n.a;return '<g transform="translate('+number(a['android:translateX'],r)+' '+number(a['android:translateY'],r)+') rotate('+number(a['android:rotation'],r)+' '+number(a['android:pivotX'],r)+' '+number(a['android:pivotY'],r)+') scale('+number(a['android:scaleX'],r,1)+' '+number(a['android:scaleY'],r,1)+')">'+n.children.map(svgNode).join('')+'</g>'}return ''};const svg='<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 '+number(n.a['android:viewportWidth'],r,24)+' '+number(n.a['android:viewportHeight'],r,24)+'">'+n.children.map(svgNode).join('')+'</svg>';return {src:'data:image/svg+xml;base64,'+Buffer.from(svg).toString('base64')}}
if(n.tag==='shape'){let css='';for(const x of n.children){const a=x.a;if(x.tag==='solid')css+='background:'+(color(a['android:color'],r)||'transparent')+';';if(x.tag==='corners')css+='border-radius:'+number(a['android:radius'],r)+'px;';if(x.tag==='stroke')css+='border:'+number(a['android:width'],r)+'px solid '+(color(a['android:color'],r)||'transparent')+';';if(x.tag==='gradient'){const start=color(a['android:startColor'],r)||'transparent',end=color(a['android:endColor'],r)||'transparent',center=color(a['android:centerColor'],r);css+='background:linear-gradient('+((90-number(a['android:angle'],r)+360)%360)+'deg,'+start+','+(center?center+',':'')+end+');'}}if(n.a['android:shape']==='oval')css+='border-radius:50%;';return {css}}
return {}}
function renderLayout(file){const xml=fs.readFileSync(file,'utf8'),tree=parse(xml),res=path.dirname(path.dirname(file)),r=resources(res);const warnings=new Set(),screens=[];
function render(node,parent){const a={...r.style(node.a.style),...node.a},short=node.tag.split('.').pop(),id=(a['android:id']||'').replace(/^@\+?id\//,'')||'node-'+node.index;const width=r.value(a['android:layout_width']),height=r.value(a['android:layout_height']),horizontal=a['android:orientation']==='horizontal',linear=short==='LinearLayout',frame=/^(FrameLayout|RelativeLayout|ConstraintLayout)$/.test(short),scroll=/ScrollView/.test(short);let css='box-sizing:border-box;position:relative;min-width:0;min-height:0;flex-shrink:0;';
for(const [axis,v] of [['width',width],['height',height]]){css+=axis+':'+(v==='match_parent'||v==='fill_parent'?'100%':v==='wrap_content'||!v?'fit-content':number(v,r)+'px')+';'}
for(const kind of ['padding','layout_margin']){const prop=kind==='padding'?'padding':'margin',base=a['android:'+kind];if(base)css+=prop+':'+number(base,r)+'px;';for(const side of ['Left','Top','Right','Bottom']){const v=a['android:'+kind+side]??a['android:'+kind+(side==='Left'?'Start':side==='Right'?'End':side)];if(v)css+=prop+'-'+side.toLowerCase()+':'+number(v,r)+'px;'}}
if(parent?.frame){const g=a['android:layout_gravity']||'left|top';css+='grid-area:1 / 1;align-self:'+(g.includes('bottom')?'end':g.includes('top')?'start':/center_vertical|(^|\|)center($|\|)/.test(g)?'center':'start')+';justify-self:'+(g.includes('right')||g.includes('end')?'end':g.includes('left')||g.includes('start')?'start':/center_horizontal|(^|\|)center($|\|)/.test(g)?'center':'start')+';';if(width==='match_parent')css+='width:auto;justify-self:stretch;';if(height==='match_parent')css+='height:auto;align-self:stretch;'}
if(parent?.linear){const weight=number(a['android:layout_weight'],r);if(weight>0)css+='flex:'+weight+' 1 0;'+(parent.horizontal?'width:0;':'height:0;');else if((parent.horizontal?width:height)==='match_parent')css+='flex-shrink:1;';const g=a['android:layout_gravity'];if(g)css+='align-self:'+(g.includes('center')?'center':g.includes('right')||g.includes('bottom')?'flex-end':'flex-start')+';';}
const gravity=a['android:gravity']||'';
if(frame)css+='display:grid;grid-template-columns:minmax(0,1fr);grid-template-rows:minmax(0,1fr);';
else if(linear){const primary=horizontal?(/right|end/.test(gravity)?'flex-end':/center_horizontal|(^|\|)center($|\|)/.test(gravity)?'center':'flex-start'):(/bottom/.test(gravity)?'flex-end':/center_vertical|(^|\|)center($|\|)/.test(gravity)?'center':'flex-start');const cross=horizontal?(/bottom/.test(gravity)?'flex-end':/center_vertical|(^|\|)center($|\|)/.test(gravity)?'center':'flex-start'):(/right|end/.test(gravity)?'flex-end':/center_horizontal|(^|\|)center($|\|)/.test(gravity)?'center':'flex-start');css+='display:flex;flex-direction:'+(horizontal?'row':'column')+';justify-content:'+primary+';align-items:'+cross+';';}
else if(scroll)css+='display:block;overflow:'+(short==='HorizontalScrollView'?'auto hidden':'hidden auto')+';';
const bg=drawable(res,a['android:background'],r);css+=(bg.css||'');if(bg.src)css+='background-image:url("'+bg.src+'");background-size:100% 100%;';
if(a['android:visibility']==='gone')css+='display:none;';else if(a['android:visibility']==='invisible')css+='visibility:hidden;';
if(a['android:alpha'])css+='opacity:'+number(a['android:alpha'],r,1)+';';
const textColor=color(a['android:textColor'],r);if(textColor)css+='color:'+textColor+';';css+='font-size:'+number(a['android:textSize'],r,14)+'px;';if(a['android:textStyle']?.includes('bold'))css+='font-weight:700;';if(a['android:textStyle']?.includes('italic'))css+='font-style:italic;';if(a['android:letterSpacing'])css+='letter-spacing:'+number(a['android:letterSpacing'],r)+'em;';
const isText=/TextView|Button|EditText/.test(short);if(isText){css+='white-space:pre-wrap;line-height:normal;overflow:hidden;';if(!linear&&!frame)css+='display:flex;align-items:'+(gravity.includes('top')?'flex-start':gravity.includes('bottom')?'flex-end':'center')+';justify-content:'+(gravity.includes('right')?'flex-end':gravity.includes('left')?'flex-start':/Button/.test(short)||gravity.includes('center')?'center':'flex-start')+';';}
let content='';if(short==='ImageView'||short==='ImageButton'){const img=drawable(res,a['android:src']||a['app:srcCompat'],r);if(img.src)content='<img alt="'+esc(a['android:contentDescription']||'')+'" draggable="false" style="width:100%;height:100%;object-fit:'+(['centerCrop'].includes(a['android:scaleType'])?'cover':a['android:scaleType']==='fitXY'?'fill':'contain')+';display:block" src="'+img.src+'">';else if(a['android:src'])warnings.add('Image non résolue : '+a['android:src']);}
else if(isText)content=esc(r.value(a['android:text'])||a['android:hint']||'').replace(/\\n/g,'\n');
if(!frame&&!linear&&!scroll&&!isText&&!/^(View|Space|ImageView|ImageButton)$/.test(short))warnings.add('Composant natif partiellement interprété : '+short);
const pages=frame?node.children.filter(n=>/Layout$/.test(n.tag.split('.').pop())&&n.a['android:layout_width']==='match_parent'&&n.a['android:layout_height']==='match_parent'):[];const group=pages.length>1&&pages.some(n=>n.a['android:visibility']==='gone')?'group-'+node.index:null;content+=node.children.map(n=>render(n,{frame,linear,horizontal,group:pages.includes(n)?group:null})).join('');if(parent?.group)screens.push({id,label:id.replace(/^(?:page|layer)/i,''),group:parent.group,hidden:a['android:visibility']==='gone'});return '<div '+(parent?.group?'data-native-screen-group="'+esc(parent.group)+'" data-native-display="'+(frame?'grid':linear?'flex':'block')+'" ':'')+'id="native-'+esc(id)+'" data-native-key="'+esc(id)+'" data-native-tag="'+esc(short)+'" style="'+esc(css)+'">'+content+'</div>'}
const body=tree.children.map(n=>render(n,null)).join('');return {body,xml,nodes:tree.children,warnings:[...warnings],screens}}
function windowProfile(android){const xml=fs.readFileSync(android.manifest,'utf8'),manifest=parse(xml),app=manifest.children[0]?.children.find(n=>n.tag==='application'),activity=app?.children.find(n=>n.tag==='activity'&&n.children.some(c=>c.tag==='intent-filter'&&c.children.some(x=>x.a['android:name']==='android.intent.action.MAIN')))||app?.children.find(n=>n.tag==='activity');const res=path.join(android.mainRoot,'res'),r=resources(res),theme=r.style(activity?.a['android:theme']||app?.a['android:theme']);const orientation=activity?.a['android:screenOrientation']||'',landscape=/landscape/i.test(orientation),tv=xml.includes('android.intent.category.LEANBACK_LAUNCHER');const fullscreen=theme['android:windowFullscreen']==='true';return {orientation,deviceKind:tv?'tv':landscape?'desktop':'phone',width:landscape?(tv?1280:915):412,height:landscape?(tv?720:412):915,topInset:fullscreen?0:28,bottomInset:fullscreen&&tv?0:48,leftInset:0,rightInset:0,fullscreen,inferred:true}}
module.exports={renderLayout,windowProfile,parse};
