const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('AppInterfaceStudio', {
  isDesktop: true,
  apkCommand: (action,payload) => ipcRenderer.invoke('apk:command',{action,payload}),
  openApk: () => ipcRenderer.invoke('android:open',{pickApk:true}),
  openAndroidLab: options => ipcRenderer.invoke('android:open',options||{}),
  onChatGptAccount: fn=>{ipcRenderer.on('chatgpt:account-status',(_e,p)=>fn(p))},
  chatGptProject: (action,payload)=>ipcRenderer.invoke('chatgpt:project',{action,payload}),
  chatGptView: payload=>ipcRenderer.invoke('chatgpt:view',payload),
  onChatGptStatus: fn=>{ipcRenderer.on('chatgpt:web-status',(_e,p)=>fn(p))},
  openUrl: value => ipcRenderer.invoke('source:open-url', value),
  pickFolder: () => ipcRenderer.invoke('source:pick-folder'),
  pickHtml: () => ipcRenderer.invoke('source:pick-html'),
  openDemo: () => ipcRenderer.invoke('source:open-demo'),
  restoreSource: source => ipcRenderer.invoke('source:restore', source),
  injectEditor: () => ipcRenderer.invoke('source:inject-editor'),
  setPreviewMode: payload => ipcRenderer.invoke('preview:set-mode', payload),
  openAsApp: payload => ipcRenderer.invoke('preview:open-app', payload),
  openInstalledApk: payload => ipcRenderer.invoke('adb:open-installed',payload||{}),
  androidGeometry: payload => ipcRenderer.invoke('adb:geometry',payload||{}),
  adbStatus: () => ipcRenderer.invoke('adb:status'),
  adbScreenshot: payload => ipcRenderer.invoke('adb:screenshot', payload || {}),
  pickReferenceImage: () => ipcRenderer.invoke('reference:pick-image'),
  pickAssetImage: () => ipcRenderer.invoke('asset:pick-image'),
  loadAssetImage: path => ipcRenderer.invoke('asset:load-image', { path }),
  assetThumbnail: path => ipcRenderer.invoke('asset:thumbnail', { path }),
  stageAssetData: payload => ipcRenderer.invoke('asset:stage-data', payload),
  auditAssets: source => ipcRenderer.invoke('source:audit-assets', { source }),
  cleanGeneratedAssets: source => ipcRenderer.invoke('source:clean-assets', { source }),
  previewPatch: payload => ipcRenderer.invoke('source:preview-patch', payload),
  applyCssToSource: payload => ipcRenderer.invoke('source:apply-css', payload),
  rollbackLastPatch: payload => ipcRenderer.invoke('source:rollback-last-patch', payload),
  listTransactions: source => ipcRenderer.invoke('source:list-transactions', { source }),
  rollbackThroughTransaction: payload => ipcRenderer.invoke('source:rollback-through', payload),
  gitStatus: payload => ipcRenderer.invoke('source:git-status', payload),
  prepareGitBranch: payload => ipcRenderer.invoke('source:git-prepare-branch', payload),
  gitPublish: payload => ipcRenderer.invoke('source:git-publish', payload),
  captureBatch: payload => ipcRenderer.invoke('capture:batch', payload),
  captureCurrentSource: payload => ipcRenderer.invoke('capture:current-source', payload),
  compareRegression: payload => ipcRenderer.invoke('regression:compare', payload),
  prepareDirectEdit: payload => ipcRenderer.invoke('source:prepare-direct-edit', payload),
  applyDirectEdit: payload => ipcRenderer.invoke('source:apply-direct-edit', payload),
  validateDirectEdit: payload => ipcRenderer.invoke('source:validate-direct-edit', payload),
  analyzeOverrides: source => ipcRenderer.invoke('source:analyze-overrides', { source }),
  cleanupOverrides: payload => ipcRenderer.invoke('source:cleanup-overrides', payload),
  analyzeCssCleanup: source => ipcRenderer.invoke('css-cleanup:analyze', { source }),
  prepareCssCleanup: payload => ipcRenderer.invoke('css-cleanup:prepare', payload),
  applyCssCleanup: payload => ipcRenderer.invoke('css-cleanup:apply', payload),
  nativeTree: payload => ipcRenderer.invoke('source:native-tree', payload),
  prepareNativeEdit: payload => ipcRenderer.invoke('source:prepare-native-edit', payload),
  applyNativeEdit: payload => ipcRenderer.invoke('source:apply-native-edit', payload),
  runTestMatrix: payload => ipcRenderer.invoke('capture:test-matrix', payload),
  replayScenario: payload => ipcRenderer.invoke('scenario:replay', payload),
  keyboardAccessibilityAudit: payload => ipcRenderer.invoke('accessibility:keyboard-audit', payload),
  profilePerformance: payload => ipcRenderer.invoke('performance:profile', payload),
  testNetwork: payload => ipcRenderer.invoke('network:test', payload),
  analyzeRoutes: payload => ipcRenderer.invoke('routes:analyze', payload),
  exportReport: payload => ipcRenderer.invoke('report:export', payload),
  saveProject: project => ipcRenderer.invoke('layout:save-project', project),
  openProject: () => ipcRenderer.invoke('layout:open-project'),
  exportPortableProject: project => ipcRenderer.invoke('layout:export-portable', project),
  importPortableProject: () => ipcRenderer.invoke('layout:import-portable'),
  saveChatGPTExport: payload => ipcRenderer.invoke('layout:save-chatgpt', payload),
  copyText: text => ipcRenderer.invoke('layout:copy-text', String(text || '')),
  appInfo: () => ipcRenderer.invoke('layout:app-info'),
  smokeTransactionRoundtrip: () => ipcRenderer.invoke('smoke:transaction-roundtrip'),
  smokeAtomicFailureRollback: () => ipcRenderer.invoke('smoke:atomic-failure-rollback'),
  smokePortableRoundtrip: () => ipcRenderer.invoke('smoke:portable-roundtrip'),
  smokeCascadeFixtures: () => ipcRenderer.invoke('smoke:cascade-fixtures'),
  smokeScenarioFixture: () => ipcRenderer.invoke('smoke:scenario-fixture'),
  smokeCssCleanupFixture: () => ipcRenderer.invoke('smoke:css-cleanup-fixture'),
  smokeRouteFixture: () => ipcRenderer.invoke('smoke:route-fixture'),
  smokeReportFixture: () => ipcRenderer.invoke('smoke:report-fixture'),
  smokeAssetCleanupFixture: () => ipcRenderer.invoke('smoke:asset-cleanup-fixture')
});

// Compatibilité avec la v1.
contextBridge.exposeInMainWorld('RadioDesktop', {
  isDesktop: true,
  saveProject: project => ipcRenderer.invoke('layout:save-project', project),
  openProject: () => ipcRenderer.invoke('layout:open-project'),
  saveChatGPTExport: payload => ipcRenderer.invoke('layout:save-chatgpt', payload),
  copyText: text => ipcRenderer.invoke('layout:copy-text', String(text || '')),
  appInfo: () => ipcRenderer.invoke('layout:app-info')
});

contextBridge.exposeInMainWorld("StudioWorkspaceApi",{dock:p=>ipcRenderer.invoke("studio:android-dock",p),onMode:fn=>ipcRenderer.on("studio:workspace-mode",(_e,p)=>fn(p)),onGeometry:fn=>ipcRenderer.on("studio:android-geometry",(_e,p)=>fn(p))});

contextBridge.exposeInMainWorld('StudioSyncApi',{command:p=>ipcRenderer.invoke('studio-sync:command',p),onStatus:fn=>ipcRenderer.on('studio-sync:status',(_e,p)=>fn(p))});
