plugins {
    id 'com.android.application'
}

android {
    namespace 'app.radiointelligente'
    compileSdk 35

    defaultConfig {
        applicationId 'app.radiointelligente'
        minSdk 23
        targetSdk 35
        versionCode 108
        versionName '1.08'
    }

    buildTypes {
        debug {
            applicationIdSuffix ''
            versionNameSuffix ''
        }
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
