const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('AppInterfaceStudio', {
  isDesktop: true,
  openUrl: value => ipcRenderer.invoke('source:open-url', value),
  pickFolder: () => ipcRenderer.invoke('source:pick-folder'),
  pickHtml: () => ipcRenderer.invoke('source:pick-html'),
  openDemo: () => ipcRenderer.invoke('source:open-demo'),
  restoreSource: source => ipcRenderer.invoke('source:restore', source),
  injectEditor: () => ipcRenderer.invoke('source:inject-editor'),
  setPreviewMode: payload => ipcRenderer.invoke('preview:set-mode', payload),
  openAsApp: payload => ipcRenderer.invoke('preview:open-app', payload),
  adbStatus: () => ipcRenderer.invoke('adb:status'),
  adbScreenshot: payload => ipcRenderer.invoke('adb:screenshot', payload || {}),
  pickReferenceImage: () => ipcRenderer.invoke('reference:pick-image'),
  pickAssetImage: () => ipcRenderer.invoke('asset:pick-image'),
  loadAssetImage: path => ipcRenderer.invoke('asset:load-image', { path }),
  assetThumbnail: path => ipcRenderer.invoke('asset:thumbnail', { path }),
  stageAssetData: payload => ipcRenderer.invoke('asset:stage-data', payload),
  auditAssets: source => ipcRenderer.invoke('source:audit-assets', { source }),
  cleanGeneratedAssets: source => ipcRenderer.invoke('source:clean-assets', { source }),
  previewPatch: payload => ipcRenderer.invoke('source:preview-patch', payload),
  applyCssToSource: payload => ipcRenderer.invoke('source:apply-css', payload),
  rollbackLastPatch: payload => ipcRenderer.invoke('source:rollback-last-patch', payload),
  listTransactions: source => ipcRenderer.invoke('source:list-transactions', { source }),
  rollbackThroughTransaction: payload => ipcRenderer.invoke('source:rollback-through', payload),
  gitStatus: payload => ipcRenderer.invoke('source:git-status', payload),
  gitPublish: payload => ipcRenderer.invoke('source:git-publish', payload),
  captureBatch: payload => ipcRenderer.invoke('capture:batch', payload),
  captureCurrentSource: payload => ipcRenderer.invoke('capture:current-source', payload),
  compareRegression: payload => ipcRenderer.invoke('regression:compare', payload),
  prepareDirectEdit: payload => ipcRenderer.invoke('source:prepare-direct-edit', payload),
  applyDirectEdit: payload => ipcRenderer.invoke('source:apply-direct-edit', payload),
  validateDirectEdit: payload => ipcRenderer.invoke('source:validate-direct-edit', payload),
  analyzeOverrides: source => ipcRenderer.invoke('source:analyze-overrides', { source }),
  cleanupOverrides: payload => ipcRenderer.invoke('source:cleanup-overrides', payload),
  nativeTree: payload => ipcRenderer.invoke('source:native-tree', payload),
  prepareNativeEdit: payload => ipcRenderer.invoke('source:prepare-native-edit', payload),
  applyNativeEdit: payload => ipcRenderer.invoke('source:apply-native-edit', payload),
  runTestMatrix: payload => ipcRenderer.invoke('capture:test-matrix', payload),
  replayScenario: payload => ipcRenderer.invoke('scenario:replay', payload),
  keyboardAccessibilityAudit: payload => ipcRenderer.invoke('accessibility:keyboard-audit', payload),
  profilePerformance: payload => ipcRenderer.invoke('performance:profile', payload),
  testNetwork: payload => ipcRenderer.invoke('network:test', payload),
  saveProject: project => ipcRenderer.invoke('layout:save-project', project),
  openProject: () => ipcRenderer.invoke('layout:open-project'),
  exportPortableProject: project => ipcRenderer.invoke('layout:export-portable', project),
  importPortableProject: () => ipcRenderer.invoke('layout:import-portable'),
  saveChatGPTExport: payload => ipcRenderer.invoke('layout:save-chatgpt', payload),
  copyText: text => ipcRenderer.invoke('layout:copy-text', String(text || '')),
  appInfo: () => ipcRenderer.invoke('layout:app-info'),
  smokeTransactionRoundtrip: () => ipcRenderer.invoke('smoke:transaction-roundtrip'),
  smokePortableRoundtrip: () => ipcRenderer.invoke('smoke:portable-roundtrip'),
  smokeCascadeFixtures: () => ipcRenderer.invoke('smoke:cascade-fixtures'),
  smokeScenarioFixture: () => ipcRenderer.invoke('smoke:scenario-fixture')
});

// Compatibilité avec la v1.
contextBridge.exposeInMainWorld('RadioDesktop', {
  isDesktop: true,
  saveProject: project => ipcRenderer.invoke('layout:save-project', project),
  openProject: () => ipcRenderer.invoke('layout:open-project'),
  saveChatGPTExport: payload => ipcRenderer.invoke('layout:save-chatgpt', payload),
  copyText: text => ipcRenderer.invoke('layout:copy-text', String(text || '')),
  appInfo: () => ipcRenderer.invoke('layout:app-info')
});
